version: "2"
services:
  web:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    env_file:
      - ./src/config/.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27018"
